//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DropZoneFileUpload.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class localhostEntities : DbContext
    {
        public localhostEntities()
            : base("name=localhostEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<UCRED> UCREDs { get; set; }
        public virtual DbSet<UFILEID> UFILEIDs { get; set; }
        public virtual DbSet<UINFO> UINFOes { get; set; }
        public virtual DbSet<UUPLD> UUPLDs { get; set; }
        public virtual DbSet<UGCINFO> UGCINFOes { get; set; }
        public virtual DbSet<UGAME> UGAMEs { get; set; }
    }
}
