//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DropZoneFileUpload.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UFILEID
    {
        public long FILEID { get; set; }
        public Nullable<int> RROSE { get; set; }
        public Nullable<int> WROSE { get; set; }
        public Nullable<System.DateTime> RTIME { get; set; }
        public Nullable<System.DateTime> WTIME { get; set; }
        public int USERID { get; set; }
    }
}
