//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DropZoneFileUpload.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UGCINFO
    {
        public int UserID { get; set; }
        public System.DateTime InsertDate { get; set; }
        public string FileID { get; set; }
        public int NetLikes { get; set; }
        public string GcNumber { get; set; }
        public string GcAmount { get; set; }
        public string GcBarCode { get; set; }
        public string GcName { get; set; }
        public string GcEmailNotification { get; set; }
        public string GcMailed { get; set; }
        public string ModifiedBy { get; set; }
    }
}
