//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DropZoneFileUpload.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UINFO
    {
        public int USERID { get; set; }
        public string ADDRESS1 { get; set; }
        public string ADDRESS2 { get; set; }
        public string CITY { get; set; }
        public Nullable<int> ZIPCODE { get; set; }
        public string STATE { get; set; }
        public string COUNTRY { get; set; }
        public string IPADRESS { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
    }
}
