//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DropZoneFileUpload.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UUPLD
    {
        public int USERID { get; set; }
        public string FILEPATH { get; set; }
        public string FILENAME { get; set; }
        public long FILEID { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public byte[] UImage { get; set; }
        public string UImageB64 { get; set; }
        public Nullable<bool> is_deleted { get; set; }
    }
}
